Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. 
Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N-i-1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [23]:
import numpy as np
#Creating function
def opmat(ipvector,n,increasing):
    if increasing:
        ip=np.array([x**y for x in l for y in range(n)]).reshape(l.size,n)
    elif not increasing:
         ip=np.array([x**(n-y-1) for x in l for y in range(n)]).reshape(l.size,n)
    return ip
#Calling function with false
ip=np.array([1,2,3])
op=opmat(ip,3,False)
print(op)
#Calling function with true
ip=np.array([1,2,3])
op1=opmat(ip,3,True)
print(op1)

[[1 1 1]
 [4 2 1]
 [9 3 1]]
[[1 1 1]
 [1 2 4]
 [1 3 9]]


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [1]:
import numpy as np
#Defining the function
def ma(l,k):
    n=len(l)
    m=n-k+1
    i=0
    movavg=[]
    while i<m:
        newwindow=l[i:i+k]
        winavg=newwindow.mean()
        movavg.append(winavg)
        i+=1
    return movavg
#Testing the function
l=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
#Calling the function
test=ma(l,k)
print (test)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
